spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST:localhost}:${PROD_DB_PORT:3306}/${PROD_DB_NAME:CRUD}
    username: ${PROD_DB_USERNAME:root}
    password: ${PROD_DB_PASSWORD:123456}

  sql:
    init:
      mode: always