management:
  endpoints:
    web:
      exposure:
        include: '*'

  info:
    env:
      enabled: true

spring:
  datasource:
    url: sql5.freemysqlhosting.net
    username: sql5672099
    password: e3d8Eu2JIr
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.MySQL8Dialect

server:
  port: 8080